services:
  mihomo:
    image: ${URL_CR_PROXY}metacubex/mihomo
    container_name: mihomo
    restart: always
    volumes:
      - ${CLASH_BASE_DIR}/resources/runtime.yaml:/root/.config/mihomo/config.yaml:ro
      # - /opt/clash/resources/public:/root/.config/mihomo/public:ro
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: "host"
    profiles:
      - mihomo
  clash:
    image: ${URL_CR_PROXY}dreamacro/clash-premium
    container_name: clash
    restart: always
    volumes:
      - ${CLASH_BASE_DIR}/resources/runtime.yaml:/root/.config/clash/config.yaml:ro
      - ${CLASH_BASE_DIR}/resources/public:/root/.config/clash/public:ro
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: "host"
    profiles:
      - clash
  # dashboard:
  #   image: ${URL_CR_PROXY}haishanh/yacd
  #   restart: always
  #   # depends_on:
  #   #   - mihomo
  #   #   - clash
  #   ports:
  #     - ${UI_PORT}:80
  #   container_name: yacd
  #   network_mode: "bridge"

  subconverter:
    image: ${URL_CR_PROXY}tindy2013/subconverter
    container_name: subconverter
    restart: always
    ports:
      - ${BIN_SUBCONVERTER_PORT}:25500
    network_mode: "bridge"
    