services:
  mihomo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URL_CR_PROXY=${URL_CR_PROXY}
    image: nelvko/proxy-kernel
    container_name: mihomo
    restart: always
    # ports:
    #   - ${MIXED_PORT}:${MIXED_PORT}
    #   - ${UI_PORT}:${UI_PORT}
    volumes:
      - /opt/clash/resources/runtime.yaml:/root/.config/mihomo/config.yaml:ro
      # - /opt/clash/resources/public:/root/.config/mihomo/public:ro
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: "host"

  web:
    image: ${URL_CR_PROXY}haishanh/yacd
    restart: always
    depends_on:
        - mihomo
    ports:
      - ${UI_PORT}:80
    container_name: web

  subconverter:
    image: ${URL_CR_PROXY}tindy2013/subconverter
    container_name: subconverter
    restart: always
    ports:
      - ${BIN_SUBCONVERTER_PORT}:25500
    network_mode: "bridge"
    